name: tokenize

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: cat before
        run: cat appsettings_tokenized.json
        
      - run: printenv
      
      - run: echo "$GITHUB_APIURL"
      
      - name: set vars as 
        run: gh variable list
        env:
          GH_TOKEN: ${{ github.token }}
        
      - uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '#{'
          tokenSuffix: '}#'
          files: '["**/*_tokenized.json"]'
        env:
          APIURL: ${{ vars.APIURL }}

      - name: cat after
        run: cat appsettings_tokenized.json
