name: tokenize

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

# for tokenization
# option 1
# env:
#   APIURL: ${{ vars.APIURL }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # option 2
      - name: Inject Variables
        uses: lindluni/actions-variable-groups@v2
        with:
          groups: |
            .github/variables/dev.yml

      - run: printenv
      - run: echo "$otherKey"
      
      - name: cat before
        run: cat appsettings_tokenized.json
        
      - uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '#{'
          tokenSuffix: '}#'
          files: '["**/*_tokenized.json"]'

      - name: cat after
        run: cat appsettings_tokenized.json
