name: tokenize

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: run build
        run: |
          echo "running build!"

  dev:
    runs-on: ubuntu-latest
    environment: dev
    needs: build
    
    # for tokenization
    # option 1 - set variable for environment and map here
    # env:
    #   APIURL: ${{ vars.APIURL }}
    
    # always have to map in secrets
    env:
      APIKEY: ${{ secrets.APIKEY }}

    steps:
      - uses: actions/checkout@v4

      # option 2 - read variables and set as env variables using action
      - name: Inject Variables
        uses: lindluni/actions-variable-groups@v2
        with:
          groups: |
            .github/variables/dev.yml
      
      - name: cat before
        run: cat appsettings_tokenized.json
        
      - uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '#{'
          tokenSuffix: '}#'
          files: '["**/*_tokenized.json"]'

      - name: cat after
        run: cat appsettings_tokenized.json
        
      - name: overwrite orig appsettings
        run: |
          rm appsettings.json
          mv appsettings_tokenized.json appsettings.json
        
  qa:
    runs-on: ubuntu-latest
    environment: qa
    needs: dev
    
    # for tokenization
    # option 1 - set variable for environment and map here
    # env:
    #   APIURL: ${{ vars.APIURL }}
    
    steps:
      - uses: actions/checkout@v4

      # option 2 - read variables and set as env variables using action
      - name: Inject Variables
        uses: lindluni/actions-variable-groups@v2
        with:
          groups: |
            .github/variables/qa.yml

      - name: cat before
        run: cat appsettings_tokenized.json
        
      - uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '#{'
          tokenSuffix: '}#'
          files: '["**/*_tokenized.json"]'

      - name: cat after
        run: cat appsettings_tokenized.json

